### ISSUE TITLE
Setting the version from other modules can break tools

### ISSUE THREAD

**Issue by robrwo** [sciurius/perl-Getopt-Long#21]
Getopt::Long::parser sets the version this way:
```perl
use Getopt::Long (); our $VERSION = $Getopt::Long::VERSION;
```
but since Getopt::Long is a core module, tools that attempt to extract the version may end up using the previously-installed or core version.

While this may be technically a bug with those tools, it is still worth being aware of. For example, a diff when upgrading the module of `cpanfile.snapshot` (generated by Carton):
```diff
-  Getopt-Long-2.54
-    pathname: J/JV/JV/Getopt-Long-2.54.tar.gz
+  Getopt-Long-2.55
+    pathname: J/JV/JV/Getopt-Long-2.55.tar.gz
     provides:
-      Getopt::Long 2.54
-      Getopt::Long::CallBack 2.54
-      Getopt::Long::Parser 2.54
+      Getopt::Long 2.55
+      Getopt::Long::CallBack 2.55
+      Getopt::Long::Parser 2.52
```

I'd recommend simply setting the $VERSION as hardcoded, and adding a simple release test to ensure that all module versions have the same version number. Since there's only three modules it shouldn't be too difficult to maintain, and will avoid any weirdness.

**Comment by robrwo** [comment]
See https://github.com/perl-carton/carton/issues/288#issuecomment-1804685770 as PAUSE made a similar mistake when parsing the module.

**Comment by sciurius** [comment]
I see your points.
Can you try https://www.squirrel.nl/pub/Getopt-Long-2.55_01.tar.gz

**Comment by robrwo** [comment]
I tried Getopt-Long-2.55_01 from CPAN, and it seems better, and works with Carton now.

**Comment by sciurius** [comment]
Thanks for testing. I'll release it as 2.56.

**Comment by jkeenan** [comment]
> Thanks for testing. I'll release it as 2.56.

This ticket appears to be closable, as both 2.56 and 2.57 are doing well on CPANtesters.
