### ISSUE TITLE
Be more precise about numeric errors

### ISSUE THREAD

**Issue by DrHyde** [sciurius/perl-Getopt-Long#26]
(copied from https://rt.cpan.org/Public/Bug/Display.html?id=136918)

I'm using GetOptionsFromArray thus:

```
    GetOptionsFromArray(\@args,
        'month=i' => \$month,
        'year=i'  => \$year
    );
```

When my arguments are things like `--year 2021.2` I get a warning:

```
    Value "2021.2" invalid for option year (number expected)
```

but 2021.2 *is* a number. It's just not an *integer*. Could you update the error message?

**Comment by sciurius** [comment]
Thank. As of 2.58 the message will be "integer number expected".

**Comment by DrHyde** [comment]
Thank you!

**Comment by DrHyde** [comment]
Any chance of releasing 2.58 any time soon? :-)

**Comment by sciurius** [comment]
On Tue, 11 Jun 2024 03:49:50 -0700, David Cantrell
***@***.***> wrote:

> Any chance of releasing 2.58 any time soon? :-)
> 

Well, soon :)

It's on its way to the CPAN.

-- Johan

**Comment by DrHyde** [comment]
Thanks!
